### ISSUE TITLE
My visulize windows is only has the supervoxel normals result.

### ISSUE THREAD

**Issue by EdwiinJunior** [fverdoja/Fast-3D-Pointcloud-Segmentation#4]
When I use your pcd file in your files without ROS. 
In my terminal I input "build/supervoxel_clusrering -p pcd/milk_cartoon_all_small_colorx_pcd", ther is a tip in my terminal "Failed to find match for field 'label'.  And the other step is good.
Last, my visulize window is only has the supervoxel normals result(whatever I choose 0-4 is ON or only choose 3 or others ), and no have others result.  No color, only white normal vector.
What's wrong? Hope your answer.

**Comment by EdwiinJunior** [comment]
My pcd file is xyz+rgb

**Comment by fverdoja** [comment]
Hi,
You have to provide a value for the `-t` argument which indicates the threshold for the final segmentation. The `-t` argument is required unless the pcd file has ground-truth label data (which the demo pcd file doesn't have). if the file had labels then if you don't provide a `-t` parameter the method chooses the threshold that minimizes the error over the ground-truth, which is useful for testing, but not really usable on real pointclouds; for those you have to provide (or learn) a threshold yourself.

Can you please tell me if the issue persists after you provide a threshold? 
Thanks.

**Comment by EdwiinJunior** [comment]
Hi,
    Thanks for your answer for my question. Your are really a good open source developer.
    When I input " "build/supervoxel_clusrering -p pcd/milk_cartoon_all_small_colorx_pcd -t 0.15", the argument comes from your perfect paper. There are some lines which are connected. Do't have any color. I try to open show 0-4, same as my before issue. Maybe there are some wrong with me. I will try agin.
    Hope your anwser.

**Comment by fverdoja** [comment]
What version of PCL and openCV are you running on? can you please send some screenshots of your issues? It's difficult to understand what the problem you are having is with only that description.

**Comment by EdwiinJunior** [comment]
![1](https://user-images.githubusercontent.com/44420314/100601287-5c549200-333d-11eb-9dba-8daf4d811334.png)
![2](https://user-images.githubusercontent.com/44420314/100601335-69718100-333d-11eb-8e8f-87e45744e8ce.png)
![Uploading 3.png…]()

**Comment by fverdoja** [comment]
From the screenshots it seems a problem with the visualization library (VTK), what version do you have of that?

**Comment by EdwiinJunior** [comment]
vtk 6.3

**Comment by EdwiinJunior** [comment]
Sorry, mabe It is my own wrong. And thanks for your patient answers. I will try agin by different VTK versions.
Thanks very much.
