### ISSUE TITLE
 about parameters 

### ISSUE THREAD

**Issue by Dweiq** [fverdoja/Fast-3D-Pointcloud-Segmentation#6]
excuse me, I have run your code many times, but the segmentation effect is not ideal, because there are too many parameters, so I would like to ask what are the specific parameters of the runtime in your example: milk_cartoon_all_small_clorox.pcd.

Hope to get your reply, thank you!

**Comment by fverdoja** [comment]
Hi, try with: `./supervoxel_clustering -p <path/to/milk.pcd> -t 0.2 --AL`
you can try changing the threshold (`-t`) to get different results...
